[package]
description = "Embeds files content into the binary in release mode, but loads it from the fs in debug"
edition = "2021"
license = "MIT"
name = "embed-file"
repository = "https://github.com/imbolc/embed-file"
version = "0.1.0"

[dependencies]

[dev-dependencies]
rusty-hook = "0.11"
